"""audit hardening org ip metadata

Revision ID: 06d9b8b16136
Revises: 1488cb13a4e2
Create Date: 2026-07-19 23:40:04.175389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d9b8b16136'
down_revision = '1488cb13a4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('context', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=60), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_audit_event_organization_id_organization'), 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_event_organization_id_organization'), type_='foreignkey')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('context')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
