"""Profile fields on user

Revision ID: 09baa7900a93
Revises: 1c78b30bf82b
Create Date: 2026-07-23 11:03:56.798976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09baa7900a93'
down_revision = '1c78b30bf82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('phone')
        batch_op.drop_column('job_title')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
