"""regulatory intelligence

Revision ID: 1488cb13a4e2
Revises: 8b492d09c605
Create Date: 2026-07-19 17:55:59.595160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1488cb13a4e2'
down_revision = '8b492d09c605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('authority', sa.String(length=80), nullable=False),
    sa.Column('jurisdiction', sa.String(length=80), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('official_url', sa.String(length=400), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_regulatory_source_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulatory_source'))
    )
    op.create_table('regulatory_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('impact_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_regulatory_change_organization_id_organization')),
    sa.ForeignKeyConstraint(['source_id'], ['regulatory_source.id'], name=op.f('fk_regulatory_change_source_id_regulatory_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulatory_change'))
    )
    op.create_table('regulatory_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('article_reference', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('obligation_type', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['regulatory_source.id'], name=op.f('fk_regulatory_requirement_source_id_regulatory_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulatory_requirement'))
    )
    op.create_table('compliance_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('control_type', sa.String(length=80), nullable=True),
    sa.Column('software_module', sa.String(length=120), nullable=True),
    sa.Column('implementation_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_compliance_control_organization_id_organization')),
    sa.ForeignKeyConstraint(['requirement_id'], ['regulatory_requirement.id'], name=op.f('fk_compliance_control_requirement_id_regulatory_requirement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_control'))
    )
    op.create_table('impact_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('affected_requirement_ids', sa.JSON(), nullable=False),
    sa.Column('affected_control_ids', sa.JSON(), nullable=False),
    sa.Column('affected_workflow_codes', sa.JSON(), nullable=False),
    sa.Column('affected_customer_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['user.id'], name=op.f('fk_impact_assessment_assessed_by_user')),
    sa.ForeignKeyConstraint(['change_id'], ['regulatory_change.id'], name=op.f('fk_impact_assessment_change_id_regulatory_change')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_assessment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impact_assessment')
    op.drop_table('compliance_control')
    op.drop_table('regulatory_requirement')
    op.drop_table('regulatory_change')
    op.drop_table('regulatory_source')
    # ### end Alembic commands ###
