"""provider integration layer

Revision ID: 1b56901c1458
Revises: e6898454b298
Create Date: 2026-07-19 07:17:14.371593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b56901c1458'
down_revision = 'e6898454b298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('external_event_id', sa.String(length=120), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_event')),
    sa.UniqueConstraint('external_event_id', name=op.f('uq_webhook_event_external_event_id'))
    )
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('adapter', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_provider_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider'))
    )
    op.create_table('normalized_compliance_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('result_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_normalized_compliance_result_customer_id_customer')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_normalized_compliance_result_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalized_compliance_result'))
    )
    op.create_table('provider_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=60), nullable=False),
    sa.Column('secret_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('fk_provider_credential_provider_id_provider')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credential'))
    )
    op.create_table('provider_health_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('fk_provider_health_status_provider_id_provider')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_health_status'))
    )
    op.create_table('raw_provider_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('verification_type', sa.String(length=40), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_raw_provider_response_customer_id_customer')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_raw_provider_response_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_provider_response'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_provider_response')
    op.drop_table('provider_health_status')
    op.drop_table('provider_credential')
    op.drop_table('normalized_compliance_result')
    op.drop_table('provider')
    op.drop_table('webhook_event')
    # ### end Alembic commands ###
