"""parties, ownership and screening matches

Revision ID: 1bd1523c74a8
Revises: 8b3f3de7e84f
Create Date: 2026-07-18 01:55:11.445402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd1523c74a8'
down_revision = '8b3f3de7e84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('country_of_residence', sa.String(length=80), nullable=True),
    sa.Column('registration_number', sa.String(length=80), nullable=True),
    sa.Column('country_of_incorporation', sa.String(length=80), nullable=True),
    sa.Column('legal_form', sa.String(length=80), nullable=True),
    sa.Column('business_activity', sa.String(length=200), nullable=True),
    sa.Column('is_pep', sa.Boolean(), nullable=False),
    sa.Column('pep_type', sa.String(length=60), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ownership_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('owner_party_id', sa.Integer(), nullable=False),
    sa.Column('owned_party_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('control_type', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['owned_party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['owner_party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_run_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('matched_name', sa.String(length=200), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('match_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_party_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_customer_root_party', 'party', ['root_party_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customer_root_party', type_='foreignkey')
        batch_op.drop_column('root_party_id')

    op.drop_table('screening_match')
    op.drop_table('screening_run')
    op.drop_table('ownership_relationship')
    op.drop_table('party')
    # ### end Alembic commands ###
