"""MFA fields on user

Revision ID: 1c78b30bf82b
Revises: ea64d3ade5c7
Create Date: 2026-07-23 09:52:29.263865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c78b30bf82b'
down_revision = 'ea64d3ade5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('mfa_method', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('mfa_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('mfa_backup_codes', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mfa_backup_codes')
        batch_op.drop_column('mfa_secret')
        batch_op.drop_column('mfa_method')
        batch_op.drop_column('mfa_enabled')

    # ### end Alembic commands ###
