"""customer portal chat: user.customer_id + customer.relationship_manager_id

Revision ID: 212f1a147cb7
Revises: 57f1e15bdfe8
Create Date: 2026-07-21 18:00:07.246924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212f1a147cb7'
down_revision = '57f1e15bdfe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship_manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_customer_relationship_manager_id_user'), 'user', ['relationship_manager_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_customer_id_customer'), 'customer', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_customer_id_customer'), type_='foreignkey')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customer_relationship_manager_id_user'), type_='foreignkey')
        batch_op.drop_column('relationship_manager_id')

    # ### end Alembic commands ###
