"""Portal invitations: invitation.customer_id

Revision ID: 2d1c26ebcfe9
Revises: e3cfe41519c3
Create Date: 2026-07-22 20:44:32.581359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1c26ebcfe9'
down_revision = 'e3cfe41519c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_invitation_customer_id_customer'), 'customer', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invitation_customer_id_customer'), type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
