"""reviews and compliance alerts

Revision ID: 363c4b32858b
Revises: 1b56901c1458
Create Date: 2026-07-19 07:45:19.272707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363c4b32858b'
down_revision = '1b56901c1458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('review_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=120), nullable=True),
    sa.Column('methodology_version', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('decision', sa.String(length=60), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], name=op.f('fk_review_assigned_to_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_review_customer_id_customer')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_review_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.create_table('compliance_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], name=op.f('fk_compliance_alert_assigned_to_user')),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_compliance_alert_case_id_case')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_compliance_alert_customer_id_customer')),
    sa.ForeignKeyConstraint(['event_id'], ['compliance_event.id'], name=op.f('fk_compliance_alert_event_id_compliance_event')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_compliance_alert_organization_id_organization')),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], name=op.f('fk_compliance_alert_resolved_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_alert'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_alert')
    op.drop_table('review')
    # ### end Alembic commands ###
