"""risk methodology factors thresholds

Revision ID: 36e83f24b9a3
Revises: 363c4b32858b
Create Date: 2026-07-19 12:40:09.426653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e83f24b9a3'
down_revision = '363c4b32858b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_methodology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_risk_methodology_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_methodology'))
    )
    op.create_table('risk_factor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('methodology_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.String(length=20), nullable=False),
    sa.Column('condition_value', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['methodology_id'], ['risk_methodology.id'], name=op.f('fk_risk_factor_methodology_id_risk_methodology')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_factor'))
    )
    op.create_table('risk_threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('methodology_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['methodology_id'], ['risk_methodology.id'], name=op.f('fk_risk_threshold_methodology_id_risk_methodology')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_threshold'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_threshold')
    op.drop_table('risk_factor')
    op.drop_table('risk_methodology')
    # ### end Alembic commands ###
