"""dual control maker checker

Revision ID: 389965e09db0
Revises: 589bf6f6cf30
Create Date: 2026-07-24 11:14:51.109085

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '389965e09db0'
down_revision = '589bf6f6cf30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dual_control_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_dual_control_policy_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dual_control_policy')),
    sa.UniqueConstraint('organization_id', 'action_type', name='uq_dc_policy_org_action')
    )
    op.create_table('dual_control_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('result_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['user.id'], name=op.f('fk_dual_control_request_decided_by_user')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_dual_control_request_organization_id_organization')),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], name=op.f('fk_dual_control_request_requested_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dual_control_request'))
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('dual_control_request')
    op.drop_table('dual_control_policy')
    # ### end Alembic commands ###
