"""team chat: rooms, members, messages

Revision ID: 57f1e15bdfe8
Revises: 66b285525fa6
Create Date: 2026-07-21 02:12:23.943814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f1e15bdfe8'
down_revision = '66b285525fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_chat_room_created_by_user')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_chat_room_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_room'))
    )
    op.create_table('chat_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], name=op.f('fk_chat_member_room_id_chat_room')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_member_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_member')),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_chat_member_room_user')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=100), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], name=op.f('fk_chat_message_room_id_chat_room')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_chat_message_sender_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    op.drop_table('chat_member')
    op.drop_table('chat_room')
    # ### end Alembic commands ###
