"""Documents carry the actual file (url, name, type, size, uploader)

Revision ID: 57fd1d229fea
Revises: 212f1a147cb7
Create Date: 2026-07-21 22:37:04.846252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57fd1d229fea'
down_revision = '212f1a147cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_document_uploaded_by_id_user'), 'user', ['uploaded_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_uploaded_by_id_user'), type_='foreignkey')
        batch_op.drop_column('uploaded_by_id')
        batch_op.drop_column('file_size')
        batch_op.drop_column('media_type')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
