"""suspicious activity reports

Revision ID: 589bf6f6cf30
Revises: 44d3ec35ae69
Create Date: 2026-07-24 09:56:40.277427

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '589bf6f6cf30'
down_revision = '44d3ec35ae69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suspicious_activity_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('report_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('transaction_ids', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], name=op.f('fk_suspicious_activity_report_approved_by_user')),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_suspicious_activity_report_case_id_case')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_suspicious_activity_report_created_by_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_suspicious_activity_report_customer_id_customer')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_suspicious_activity_report_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suspicious_activity_report'))
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('suspicious_activity_report')
    # ### end Alembic commands ###
