"""user_permissions: per-user special authorizations

Revision ID: 66b285525fa6
Revises: ec7da8eb0df4
Create Date: 2026-07-21 00:54:28.653426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b285525fa6'
down_revision = 'ec7da8eb0df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk_user_permissions_permission_id_permission')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_permissions_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', name=op.f('pk_user_permissions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
