"""Documents: customer description + reason returned

Revision ID: 7c21292339d1
Revises: dff6469a59d7
Create Date: 2026-07-22 10:34:17.465698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c21292339d1'
down_revision = 'dff6469a59d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
