"""workflow engine

Revision ID: 8b492d09c605
Revises: 36e83f24b9a3
Create Date: 2026-07-19 13:08:11.192169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b492d09c605'
down_revision = '36e83f24b9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('applies_case_type', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workflow_definition_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_definition'))
    )
    op.create_table('workflow_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approver_role', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], name=op.f('fk_workflow_step_definition_id_workflow_definition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_step'))
    )
    op.create_table('workflow_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_workflow_instance_case_id_case')),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], name=op.f('fk_workflow_instance_definition_id_workflow_definition')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workflow_instance_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_instance'))
    )
    op.create_table('workflow_step_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approver_role', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['user.id'], name=op.f('fk_workflow_step_state_completed_by_user')),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instance.id'], name=op.f('fk_workflow_step_state_instance_id_workflow_instance')),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_step.id'], name=op.f('fk_workflow_step_state_step_id_workflow_step')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_step_state'))
    )
    op.create_table('approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('step_state_id', sa.Integer(), nullable=False),
    sa.Column('required_role', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['user.id'], name=op.f('fk_approval_decided_by_user')),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instance.id'], name=op.f('fk_approval_instance_id_workflow_instance')),
    sa.ForeignKeyConstraint(['step_state_id'], ['workflow_step_state.id'], name=op.f('fk_approval_step_state_id_workflow_step_state')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval')
    op.drop_table('workflow_step_state')
    op.drop_table('workflow_instance')
    op.drop_table('workflow_step')
    op.drop_table('workflow_definition')
    # ### end Alembic commands ###
