"""Compliance Copilot: conversations + messages

Revision ID: aca8d73200a7
Revises: 06d9b8b16136
Create Date: 2026-07-20 09:26:58.973664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca8d73200a7'
down_revision = '06d9b8b16136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_conversation_customer_id_customer')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_conversation_organization_id_organization')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_conversation_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation'))
    )
    op.create_table('assistant_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_assistant_message_conversation_id_conversation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_message'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistant_message')
    op.drop_table('conversation')
    # ### end Alembic commands ###
