"""retention fields

Revision ID: c53ac68ba2e9
Revises: 389965e09db0
Create Date: 2026-07-24 11:32:22.982813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c53ac68ba2e9'
down_revision = '389965e09db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_retention_months', sa.Integer(), server_default='60', nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('data_retention_months')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
