"""management: assignment rules and SLA configuration

Revision ID: c663c1452563
Revises: dcc62561c694
Create Date: 2026-07-18 17:06:00.573292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c663c1452563'
down_revision = 'dcc62561c694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('case_priority', sa.String(length=20), nullable=False),
    sa.Column('target_hours', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('case_type', sa.String(length=80), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('required_role', sa.String(length=40), nullable=True),
    sa.Column('required_skill', sa.String(length=80), nullable=True),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_assigned_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_rule')
    op.drop_table('sla_configuration')
    # ### end Alembic commands ###
