"""Customer conversations: chat_room.customer_id + case.team_id

Revision ID: d8cc068e2450
Revises: 57fd1d229fea
Create Date: 2026-07-21 23:49:41.845565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cc068e2450'
down_revision = '57fd1d229fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_case_team_id_team'), 'team', ['team_id'], ['id'])

    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_room_customer_id'), ['customer_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_chat_room_customer_id_customer'), 'customer', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_room_customer_id_customer'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_room_customer_id'))
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_case_team_id_team'), type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
