"""Sanctioned wallet addresses from the OFAC SDN

Revision ID: dff6469a59d7
Revises: d8cc068e2450
Create Date: 2026-07-22 00:50:45.857765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff6469a59d7'
down_revision = 'd8cc068e2450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanctioned_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('asset', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=160), nullable=False),
    sa.Column('address_normalized', sa.String(length=160), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=400), nullable=True),
    sa.Column('programs', sa.JSON(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['sanctioned_entity.id'], name=op.f('fk_sanctioned_wallet_entity_id_sanctioned_entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sanctioned_wallet')),
    sa.UniqueConstraint('source', 'asset', 'address_normalized', name='uq_sanctioned_wallet_addr')
    )
    with op.batch_alter_table('sanctioned_wallet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sanctioned_wallet_address_normalized'), ['address_normalized'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sanctioned_wallet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sanctioned_wallet_address_normalized'))

    op.drop_table('sanctioned_wallet')
    # ### end Alembic commands ###
