"""Tasks link to the requirement they chase

Revision ID: e3cfe41519c3
Revises: 7c21292339d1
Create Date: 2026-07-22 15:03:25.815788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cfe41519c3'
down_revision = '7c21292339d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_code', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('requirement_code')

    # ### end Alembic commands ###
