"""kyc profile fields and requirements

Revision ID: e6898454b298
Revises: a86a6c8149e1
Create Date: 2026-07-19 02:47:18.309802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6898454b298'
down_revision = 'a86a6c8149e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('applies_customer_type', sa.String(length=20), nullable=False),
    sa.Column('min_risk_rank', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=80), nullable=True),
    sa.Column('data_field', sa.String(length=60), nullable=True),
    sa.Column('doc_type', sa.String(length=60), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_requirement_definition_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_definition'))
    )
    op.create_table('profile_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_profile_field_customer_id_customer')),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], name=op.f('fk_profile_field_verified_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_field'))
    )
    op.create_table('requirement_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('waived_by', sa.Integer(), nullable=True),
    sa.Column('waived_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_requirement_instance_customer_id_customer')),
    sa.ForeignKeyConstraint(['definition_id'], ['requirement_definition.id'], name=op.f('fk_requirement_instance_definition_id_requirement_definition')),
    sa.ForeignKeyConstraint(['waived_by'], ['user.id'], name=op.f('fk_requirement_instance_waived_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_instance'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_instance')
    op.drop_table('profile_field')
    op.drop_table('requirement_definition')
    # ### end Alembic commands ###
