"""Email tokens + email_verified

Revision ID: ea64d3ade5c7
Revises: f7498487f151
Create Date: 2026-07-23 09:30:29.762488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea64d3ade5c7'
down_revision = 'f7498487f151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_email_token_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_token'))
    )
    with op.batch_alter_table('email_token', schema=None) as batch_op:
        batch_op.create_index('ix_email_token_lookup', ['purpose', 'token_hash'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('email_token', schema=None) as batch_op:
        batch_op.drop_index('ix_email_token_lookup')

    op.drop_table('email_token')
    # ### end Alembic commands ###
