"""Public watchlists: sanctioned entities + imports

Revision ID: ec7da8eb0df4
Revises: aca8d73200a7
Create Date: 2026-07-20 14:13:34.769352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7da8eb0df4'
down_revision = 'aca8d73200a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanctioned_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('external_id', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('name_normalized', sa.String(length=400), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('aliases_normalized', sa.JSON(), nullable=False),
    sa.Column('programs', sa.JSON(), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sanctioned_entity')),
    sa.UniqueConstraint('source', 'external_id', name='uq_sanctioned_entity_source_external')
    )
    with op.batch_alter_table('sanctioned_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sanctioned_entity_name_normalized'), ['name_normalized'], unique=False)

    op.create_table('watchlist_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('live', sa.Boolean(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_import'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_import')
    with op.batch_alter_table('sanctioned_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sanctioned_entity_name_normalized'))

    op.drop_table('sanctioned_entity')
    # ### end Alembic commands ###
