"""Revoked token blocklist for logout

Revision ID: f7498487f151
Revises: 6916fabd6225
Create Date: 2026-07-23 00:34:29.457566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7498487f151'
down_revision = '6916fabd6225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_revoked_token_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_token')),
    sa.UniqueConstraint('jti', name=op.f('uq_revoked_token_jti'))
    )
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.create_index('ix_revoked_token_jti', ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.drop_index('ix_revoked_token_jti')

    op.drop_table('revoked_token')
    # ### end Alembic commands ###
