"""Shared SQLAlchemy foundation for the domain models.

All model modules import `db` and `utcnow` from here. Cross-module relationships
use string class names (e.g. Mapped["User"]) which SQLAlchemy resolves through
the shared class registry — no cross-module imports needed.
"""
from datetime import datetime, timezone

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import MetaData

# Automatic constraint naming. Without this, autogenerated migrations emit
# UNNAMED foreign keys (create_foreign_key(None, ...)) which crash SQLite's
# batch mode with "ValueError: Constraint must have a name". With the
# convention, every new constraint gets a deterministic name and `flask db
# migrate` output runs unmodified on both SQLite and PostgreSQL.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

db = SQLAlchemy(metadata=MetaData(naming_convention=NAMING_CONVENTION))


def utcnow():
    # Naive UTC: the DateTime columns are timezone-naive, and drivers (notably
    # sqlite) drop tzinfo on round-trip. Keeping everything naive-UTC avoids
    # "can't compare offset-naive and offset-aware datetimes" at read time.
    return datetime.now(timezone.utc).replace(tzinfo=None)
